// Generated by CoffeeScript 1.3.3
(function() {
  var Attack;

  Attack = (function() {

    function Attack(app, allTerritories, territories, actionController, callBackContext, callBackFunction) {
      var t, _i, _len, _ref;
      this.app = app;
      this.allTerritories = allTerritories;
      this.territories = territories;
      this.actionController = actionController;
      this.callBackContext = callBackContext;
      this.callBackFunction = callBackFunction;
      _ref = this.territories;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        this.territories_id.push(t.id);
      }
      this.modal = $('.modal-div#attack');
      this.nomeAtk = this.modal.find('#nome_atk');
      this.nomeDef = this.modal.find('#nome_def');
      this.troopsAtk = this.modal.find('#troops_atk');
      this.troopsDef = this.modal.find('#troops_def');
      this.selectTroops = this.modal.find('#qtd_troops');
      this.atkButton = this.modal.find('#btnattack');
      this.resultDiv = this.modal.find('#result');
      this.chooseOrigin();
    }

    Attack.prototype.chooseOrigin = function() {
      this.origin_id = null;
      this.destiny_id = null;
      this.actionController.open("Ataque", "Escolha um território para ser a origem do ataque");
      $('path').hover(function(o) {
        if ($.inArray($(o.currentTarget).attr('id'), this.territories_id)) {
          return $(o.currentTarget).attr('stroke-width', 2);
        }
      }, function(o) {
        if ($(o.currentTarget).attr('id') !== this.origin_id) {
          return $(o.currentTarget).attr('stroke-width', 1);
        }
      });
      return $('path').click(function(o) {
        this.origin_id = $(o.currentTarget).attr('id');
        return this.chooseDestiny();
      });
    };

    Attack.prototype.chooseDestiny = function() {
      var nome;
      $('path').off("hover click");
      nome = this.allTerritories[this.origin_id].nome;
      this.actionController.open("Ataque", "Escolha um território alvo<br/>Atacando de <b>" + nome + "</b>");
      $('path').hover(function(o) {
        if ($.inArray($(o.currentTarget).attr('id'), this.allTerritories([this.origin_id].vizinhos))) {
          return $(o.currentTarget).attr('stroke-width', 2);
        }
      }, function(o) {
        if ($(o.currentTarget).attr('id') !== this.destiny_id) {
          return $(o.currentTarget).attr('stroke-width', 1);
        }
      });
      return $('path').click(function(o) {
        this.destiny_id = $(o.currentTarget).attr('id');
        return this.attackWindow();
      });
    };

    Attack.prototype.attackWindow = function() {
      var qtd_troops;
      $('path').off("hover click");
      this.actionController.hide();
      this.nomeAtk.text(this.allTerritories[this.origin_id].nome);
      this.nomeDef.text(this.allTerritories[this.destiny_id].nome);
      this.troopsAtk.text($('#l' + this.origin_id + ' tspan').text());
      this.troopsDef.text($('#l' + this.destiny_id + ' tspan').text());
      qtd_troops = parseInt($('#l' + this.origin_id + ' tspan').text())(-1);
      if (qtd_troops > 3) {
        qtd_troops = 3;
      }
      this.selectTroops.html("");
      while (qtd_troops > 0) {
        this.selectTroops.append("<option value=\"" + qtd_troops + "\">" + qtd_troops + "</option>");
        qtd_troops--;
      }
      return this.app.openModal(this.modal);
    };

    return Attack;

  })();

}).call(this);
