// Generated by CoffeeScript 1.3.3

  var PlayerListController;

  PlayerListController = (function() {

    function PlayerListController(app) {
      this.app = app;
      this.controllerName = 'playerList';
      this.listElmnt = $('div#players');
    }

    PlayerListController.prototype.update = function(args) {
      var nick, _i, _len, _ref, _results;
      this.listElmnt.html('');
      _ref = args.list;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        nick = _ref[_i];
        _results.push(this.listElmnt.append("<div class='nick'>" + nick + "</div>"));
      }
      return _results;
    };

    return PlayerListController;

  })();


