// Generated by CoffeeScript 1.3.3

  var AppController;

  AppController = (function() {

    function AppController(wsAddr) {
      var self;
      this.wsAddr = wsAddr;
      this.conn = null;
      this.user = 'nick';
      this.controllers = {};
      self = this;
      $('.closebtn').click(function() {
        return self.closeModal($(this).parent());
      });
    }

    AppController.prototype.add_controller = function(obj) {
      return this.controllers[obj.controllerName] = obj;
    };

    AppController.prototype.openModal = function(elmnt) {
      $('.modal-overlay').show();
      return elmnt.show();
    };

    AppController.prototype.closeModal = function(elmnt) {
      elmnt.hide();
      return $('.modal-overlay').hide();
    };

    AppController.prototype.start = function() {
      var _this = this;
      this.conn = new WSConnection(this.wsAddr);
      this.conn.socket.onopen = function() {
        return _this.conn.refreshStatus();
      };
      this.conn.socket.onclose = function() {
        return _this.conn.refreshStatus();
      };
      return this.conn.socket.onmessage = function(msg) {
        var c_name, controller, msgObj;
        msgObj = eval("(" + msg.data + ")");
        c_name = msgObj.controller;
        controller = _this.controllers[c_name];
        if (msgObj.params === '') {
          controller[msgObj.action]();
        }
        if (msgObj.params !== '') {
          return controller[msgObj.action](msgObj.params);
        }
      };
    };

    return AppController;

  })();


